language: android
jdk: openjdk9

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache

before_install:
  # In travis android block, deprecated 'android' tool will be used to install.
  # Use the new sdkmanager for newer versions of the tools.
  # Also jdk8 is required to run sdkmanager -.-
  - jdk_switcher use oraclejdk8
  - echo y | sdkmanager "tools" > /dev/null
  - echo y | sdkmanager "platform-tools" > /dev/null
  - echo y | sdkmanager "platforms;android-30" > /dev/null
  - echo y | sdkmanager "emulator" > /dev/null
  - echo y | sdkmanager "system-images;android-30;google_apis;x86" > /dev/null

before_script:
  # Create emulator
  - echo no | avdmanager create avd --force -n test -k "system-images;android-30;google_apis;x86"

script:
  - JAVA_HOME=/home/travis/openjdk9 ./build.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)
