language: android
jdk: oraclejdk8
sudo: false

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache

android:
  components:
    - tools
    - platform-tools
    - tools
    - build-tools-26.0.2
    - android-22
    - sys-img-armeabi-v7a-android-22
    - extra-android-m2repository

before_install:
  # in android block, deprecated 'android' tool will be used to install.
  # android-28 package has a wrong checksum there, so we use new sdkmanager for
  # installation
  - yes | sdkmanager "platforms;android-28"

before_script:
  # Create emulator
  - echo no | android create avd --force -n test -t android-22

script:
  - ./build.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)
