language: android
jdk: oraclejdk8
sudo: false

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache

env:
  - TARGET_API=22 TARGET_ABI=armeabi-v7a
  - TARGET_API=23 TARGET_ABI=armeabi-v7a
  - TARGET_API=24 TARGET_ABI=armeabi-v7a
  - TARGET_API=25 TARGET_ABI=armeabi-v7a

android:
  components:
    - tools

before_install:
  # Install latest emulator images
  # suppressing output of sdkmanager to keep log under 4MB (travis limit)
  - yes | sdkmanager tools
  - yes | sdkmanager --licenses
  - sdkmanager --install platform-tools > /dev/null
  - sdkmanager --install "build-tools;26.0.2" > /dev/null
  - sdkmanager --install "platforms;android-27" > /dev/null
  - sdkmanager --install "system-images;android-$TARGET_API;google_apis;$TARGET_ABI" > /dev/null
  - sdkmanager --install "extras;google;m2repository" > /dev/null
  - sdkmanager --install emulator > /dev/null

before_script:
  # Create emulator
  - echo no | avdmanager create avd --force --name test --package "system-images;android-$TARGET_API;google_apis;$TARGET_ABI"

script:
  - ./build.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)
